// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20181126045227_StudentMigr")]
    partial class StudentMigr
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication1.Models.Batch", b =>
                {
                    b.Property<Guid>("batchId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("batchName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("batchId");

                    b.ToTable("Batch");
                });

            modelBuilder.Entity("WebApplication1.Models.Student", b =>
                {
                    b.Property<Guid>("studentId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("batchId");

                    b.Property<string>("studentName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("studentId");

                    b.ToTable("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
